### ISSUE TITLE
Does txZMQ support iocp reactor

### ISSUE THREAD

**Issue by dynamicgl** [smira/txZMQ#60]
Hi.

  I noticed ZMQconnection need to call addReader method which is missing in IOCP reactor. I am curious whether txZMQ supports iocp reactor or not. Thanks.

**Comment by smira** [comment]
I haven't used IOCP reactor, but all reactors should have the same interface I believe.

http://twistedmatrix.com/documents/10.1.0/api/twisted.internet.iocpreactor.reactor.IOCPReactor.html 

It looks like it has addReader method.

**Comment by ygl-rg** [comment]
Hi
  
  after poking around https://github.com/twisted/twisted/blob/trunk/twisted/internet/iocpreactor/reactor.py

  I think addReader isn't implemented in IOCPReactor so txzmq won't work with IOCPReactor.

**Comment by dynamicgl** [comment]
Hi

after poking around https://github.com/twisted/twisted/blob/trunk/twisted/internet/iocpreactor/reactor.py

I think addReader isn't implemented in IOCPReactor so txzmq won't work with IOCPReactor.
