### ISSUE TITLE
pub_sub.py example doesn't seem to work

### ISSUE THREAD

**Issue by matthewatabet** [smira/txZMQ#62]
Hi there!

I can't get the pub_sub.py example to work. Here's the commands I'm running:

./pub_sub.py --endpoint tcp://hopscotch:5050 --mode=publisher
./pub_sub.py --endpoint tcp://hopscotch:5050 --mode=subscriber

The publisher appears to be publishing:
publishing '1430422027.98'
publishing '1430422028.98'
publishing '1430422029.98'
publishing '1430422030.98'

But, the subscriber doesn't seem to be picking up the messages. Any pointers on debugging this?

**Comment by smira** [comment]
@matthewatabet you need to specify `--method` as well, one should `connect`, another should `bind`.

**Comment by matthewatabet** [comment]
thanks, that worked!
