### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frenzymadness** [smira/txZMQ#68]
Hello.

Could you please make a new release (here and on PyPI)? Current master contains some improvements of Python3 compatibility which will be handy when I will update Fedora package with Python3 subpackage.

Thank you and have a nice day.
Lumir

**Comment by smira** [comment]
0.8.0 has been released today, sorry for the delay

**Comment by frenzymadness** [comment]
Hello.

Thank you very much. Could you also please make a new release on GitHub?

**Comment by smira** [comment]
sure, done!
