### ISSUE TITLE
Change txZMQ (from GPL) to a more permissive license (at least LGPL)

### ISSUE THREAD

**Issue by ambsw-technology** [smira/txZMQ#78]
Just want to confirm that you are intentionally prohibiting distribution of this package along with proprietary software.  While GPL is certainly a valid license for a library, the [LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL) is more common for libraries (e.g. `psycopg2`) -- and you (appear to) have licensed other packages under more permissive licenses like MPL and MIT.

**Comment by smira** [comment]
yep, that was not the best choice for this library, but I don't think it would be easy to change the license today - project has 16 contributors. I have no issues changing the license to anything more permissive given that other contributors agree with their changes being re-licensed

**Comment by ambsw-technology** [comment]
That occured to me too, but 16 isn't crazy so I skimmed the contributions:

 - lvh "contributed" a simple rename so no code there
 - the following contributors only modified a file in the examples folder: aleksclark, davidjfelix, stenote,  eagafonov
 - aleksi's changes were all code style (i.e. whitespace), but they rewrote [one block of code](https://github.com/smira/txZMQ/commit/6bc3dfb307dc2620ead24f863d8c07f36886736f#diff-1d16aeac61f5bfd6c6a61ad1ce899cffL43) in a way that didn't affection functionality.

So strictly speaking, 

 - You only need approval from 8 other contributors:  j0s, jamesharr, mordae, fladi, arnimarj, nnseva ralphbean, and tisdall to relicense the core
 - You should ask AlekSi, but *could* revert that one code change if they object
 - If you can get approval from the last 4x (aleksclark, davidjfelix, stenote, eagafonov), you can include the examples.  Otherwise, I'd rename this repo `txZMQ-gpl` and move everything but the examples to a new repo under the new license.

I was going to at-tag all of the critical contributors, but it'll probably be better if it comes from you.  I suspect most/all will follow your lead if you advocate for a particular license.  If you prefer something very permissive (e.g. BSD), you should probably suggest several options (including LGPL) and ask them to mark any/all that they approve of.  That will ensure you can adopt a more permissive license even if some object to the one you suggest.

**Comment by smira** [comment]
thanks for the work you did, @ambsw-technology!

So, let's start the vote here on re-licensing. [ZeroMQ](http://zeromq.org/area:licensing) itself is licensed under LGPL + static link exception, and they plan to move to more permissive MPL v2. As txZMQ is fairly straightfoward wrapper around ZeroMQ, I don't think it should have a license which is more strict than ZeroMQ. 

There are three options for txZMQ as I see:

1. Relicense under LGPL (more strict)
2. Relicense under MPLv2 (more permissive)
3. Keep it under GPL.

My vote is to go with MPLv2.

I would like to ask all the past contributors to respond whether you're okay to relicense your contribution under LGPL/MPLv2. You can either accept both options, one of them, or tell that license change is not acceptable for your, so you would like to see your work kept under GPL.

Thanks.

Contributors:

* @j0s 
* @jamesharr 
* @mordae 
* @fladi 
* @arnimarj 
* @nnseva 
* @ralphbean 
* @tisdall 

* @AlekSi 

* @aleksclark 
* @DavidJFelix 
* @stenote 
* @eagafonov

**Comment by AlekSi** [comment]
:+1: for any option, up to you.

**Comment by tisdall** [comment]
I'm partial to MIT for it's permissiveness, but I relinquish my rights over my contributions to @smira to choose a license.  Twisted seems to use an MIT license.

**Comment by j0s** [comment]
I'm also fine with any of the options.

**Comment by mordae** [comment]
Any option is fine, but I'd prefer LGPL.

**Comment by jamesharr** [comment]
I'm ok with any of the options

**Comment by DavidJFelix** [comment]
Send me a CLA or release and I'll sign it to allow for **any** relicense of my contribution. If you asked me what I preferred? MIT or Apache2.

**Comment by eagafonov** [comment]
Both LGPL and MPL are fine for me.

**Comment by ambsw-technology** [comment]
A quick update on the progress.  Currently, the most permissive license approved by respondents is MPL.  LGPL is also still on the table.  Here's the status of the approvals (@ tagging the ones we still need):

Must have:

- ~j0s~
- ~jamesharr~ (requested a CLA; I'll tweak an existing one if/when we get an OK from the rest of the must haves)
- ~mordae~
- @fladi
- @arnimarj
- @nnseva
- @ralphbean
- ~tisdall~

Good to Have:

- ~AlekSi~

To relicense examples:

- @aleksclark
- ~DavidJFelix~
- @stenote
- ~eagafonov~

**Comment by nnseva** [comment]
approved

**Comment by ralphbean** [comment]
I approve both options: LGPL/MPLv2

**Comment by fladi** [comment]
Any option is fine, but I'd too prefer LGPL.

**Comment by arnimarj** [comment]
Hi. I'm happy with any of the options.

**Comment by aleksclark** [comment]
I approve LGPL or MPLv2

**Comment by smira** [comment]
:+1: it just took 2.5 years to get there.

I will send a PR to relicense the code under MPLv2 as it's more permissive and it feels like this software is not being widely used.

**Comment by smira** [comment]
This repositoriy is now under MPLv2 and version 1.0.0 released.
